/*
  PipZoNe Trade Code Generator

  Format:

  PZ-000001
  PZ-000002
  PZ-000003

  IMPORTANT:
  This version keeps the sequence in the browser.

  For the final production version, the sequence should be
  generated by Supabase/database so two admins can never
  generate the same code.
*/


const generateBtn = document.getElementById("generateBtn");

const generatedCode =
  document.getElementById("generatedCode");

const adjustmentType =
  document.getElementById("adjustmentType");

const percentage =
  document.getElementById("percentage");

const message =
  document.getElementById("message");

const historyList =
  document.getElementById("historyList");


/* --------------------------------
   Load saved sequence
-------------------------------- */

let sequence =
  Number(localStorage.getItem("pipzone_trade_code_sequence")) || 0;


/* --------------------------------
   Load history
-------------------------------- */

let history =
  JSON.parse(
    localStorage.getItem("pipzone_trade_codes_history") || "[]"
  );


/* --------------------------------
   Create Code
-------------------------------- */

function createCode() {

  sequence++;

  localStorage.setItem(
    "pipzone_trade_code_sequence",
    sequence
  );


  return "PZ-" +
    String(sequence).padStart(6, "0");
}


/* --------------------------------
   Generate Code
-------------------------------- */

generateBtn.addEventListener("click", function () {

  const pct = Number(percentage.value);

  if (!pct || pct <= 0 || pct > 100) {

    message.textContent =
      "Please enter a valid percentage.";

    return;
  }


  const code = createCode();

  generatedCode.value = code;


  const type =
    adjustmentType.value;


  const typeText =
    type === "increase"
      ? "Increase"
      : "Decrease";


  const item = {

    code: code,

    type: typeText,

    percentage: pct.toFixed(2),

    createdAt:
      new Date().toLocaleString()

  };


  history.unshift(item);


  localStorage.setItem(
    "pipzone_trade_codes_history",
    JSON.stringify(history)
  );


  message.textContent =
    "Code generated successfully.";


  renderHistory();

});


/* --------------------------------
   History
-------------------------------- */

function renderHistory() {

  if (!history.length) {

    historyList.innerHTML = `
      <div class="empty">
        No codes generated yet.
      </div>
    `;

    return;
  }


  historyList.innerHTML =
    history.map(item => {

      return `

        <div class="history-item">

          <div class="history-code">
            ${escapeHtml(item.code)}
          </div>

          <div class="history-info">

            ${escapeHtml(item.type)}
            •
            ${escapeHtml(item.percentage)}%

            <br>

            ${escapeHtml(item.createdAt)}

          </div>

        </div>

      `;

    }).join("");
}


/* --------------------------------
   Security helper
-------------------------------- */

function escapeHtml(value) {

  return String(value)

    .replaceAll("&", "&amp;")

    .replaceAll("<", "&lt;")

    .replaceAll(">", "&gt;")

    .replaceAll('"', "&quot;")

    .replaceAll("'", "&#039;");

}


/* --------------------------------
   Initial history
-------------------------------- */

renderHistory();
